version: 0.2

# CodeBuild project to build Strands Lambda layer with installed MCP servers
# Reads from DynamoDB to get account's installed servers and builds a layer

env:
  variables:
    PYTHON_VERSION: "3.12"
  parameter-store:
    MCP_SERVERS_TABLE: /lma/mcp-servers-table-name

phases:
  pre_build:
    commands:
      - echo "=== MCP Layer Builder ==="
      - echo "Account ID: $AWS_ACCOUNT_ID"
      - echo "Region: $AWS_DEFAULT_REGION"
      - echo "Action: $ACTION"
      - echo "MCP Servers Table: $MCP_SERVERS_TABLE"
      
      # Install dependencies
      - echo "Installing build dependencies..."
      - apt-get update -qq
      - apt-get install -y -qq jq zip > /dev/null
      - npm install -g npm@latest
      
  build:
    commands:
      - echo "=== Querying DynamoDB for installed MCP servers ==="
      - |
        SERVERS_JSON=$(aws dynamodb query \
          --table-name "$MCP_SERVERS_TABLE" \
          --key-condition-expression "AccountId = :accountId" \
          --expression-attribute-values "{\":accountId\":{\"S\":\"$AWS_ACCOUNT_ID\"}}" \
          --output json)
      
      - echo "Query result:"
      - echo "$SERVERS_JSON" | jq '.'
      
      - SERVER_COUNT=$(echo "$SERVERS_JSON" | jq '.Items | length')
      - echo "Found $SERVER_COUNT installed MCP servers"
      
      - |
        if [ "$SERVER_COUNT" -eq "0" ]; then
          echo "No MCP servers installed - creating empty layer"
          mkdir -p layer/nodejs
          cd layer/nodejs
          npm init -y
          cd ../..
        else
          echo "=== Building layer with MCP servers ==="
          mkdir -p layer/nodejs
          cd layer/nodejs
          
          # Create package.json with all installed servers
          echo "Creating package.json..."
          cat > package.json <<EOF
        {
          "name": "lma-mcp-servers-layer",
          "version": "1.0.0",
          "description": "MCP servers for LMA Strands agent",
          "dependencies": {
        EOF
          
          # Add each server as dependency
          FIRST=true
          echo "$SERVERS_JSON" | jq -r '.Items[] | "\(.NpmPackage.S)@\(.Version.S // "latest")"' | while read package; do
            if [ "$FIRST" = true ]; then
              echo "    \"${package%@*}\": \"${package#*@}\"" >> package.json
              FIRST=false
            else
              echo "    ,\"${package%@*}\": \"${package#*@}\"" >> package.json
            fi
          done
          
          # Close package.json
          cat >> package.json <<EOF
          }
        }
        EOF
          
          echo "Generated package.json:"
          cat package.json
          
          # Install all MCP server packages
          echo "Installing MCP server packages..."
          npm install --production --no-optional
          
          echo "Installation complete. Installed packages:"
          ls -la node_modules/ | head -20
          
          cd ../..
        fi
      
      - echo "=== Packaging layer ==="
      - cd layer
      - zip -r ../mcp-layer.zip . -q
      - cd ..
      - LAYER_SIZE=$(du -h mcp-layer.zip | cut -f1)
      - echo "Layer size: $LAYER_SIZE"
      
      - echo "=== Publishing Lambda layer ==="
      - |
        LAYER_VERSION=$(aws lambda publish-layer-version \
          --layer-name "${STACK_NAME}-mcp-servers" \
          --description "MCP servers for account $AWS_ACCOUNT_ID" \
          --zip-file fileb://mcp-layer.zip \
          --compatible-runtimes python3.12 \
          --query 'Version' \
          --output text)
      
      - echo "Published layer version: $LAYER_VERSION"
      
      - echo "=== Updating Strands Lambda function ==="
      - FUNCTION_NAME="STRANDS-${STACK_NAME}-MeetingAssist"
      - echo "Function name: $FUNCTION_NAME"
      
      - |
        LAYER_ARN="arn:aws:lambda:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:layer:${STACK_NAME}-mcp-servers:${LAYER_VERSION}"
        echo "Layer ARN: $LAYER_ARN"
      
      - |
        # Get current layers
        CURRENT_LAYERS=$(aws lambda get-function-configuration \
          --function-name "$FUNCTION_NAME" \
          --query 'Layers[].LayerArn' \
          --output json)
        
        echo "Current layers: $CURRENT_LAYERS"
        
        # Filter out old MCP layer versions, keep other layers
        NEW_LAYERS=$(echo "$CURRENT_LAYERS" | jq -r --arg layer "$LAYER_ARN" \
          'map(select(. | contains("mcp-servers") | not)) + [$layer] | join(" ")')
        
        echo "New layers: $NEW_LAYERS"
        
        # Update function with new layer
        aws lambda update-function-configuration \
          --function-name "$FUNCTION_NAME" \
          --layers $NEW_LAYERS
      
      - echo "✓ Lambda function updated with new MCP layer"
      
      - echo "=== Updating DynamoDB server statuses ==="
      - |
        if [ "$ACTION" = "INSTALL_MCP_SERVER" ] && [ -n "$SERVER_ID" ]; then
          aws dynamodb update-item \
            --table-name "$MCP_SERVERS_TABLE" \
            --key "{\"AccountId\":{\"S\":\"$AWS_ACCOUNT_ID\"},\"ServerId\":{\"S\":\"$SERVER_ID\"}}" \
            --update-expression "SET #status = :status, UpdatedAt = :updated" \
            --expression-attribute-names '{"#status":"Status"}' \
            --expression-attribute-values "{\":status\":{\"S\":\"ACTIVE\"},\":updated\":{\"S\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}}"
          echo "✓ Updated server status to ACTIVE"
        fi

  post_build:
    commands:
      - echo "=== Build Complete ==="
      - echo "MCP servers layer built and deployed successfully"

artifacts:
  files:
    - mcp-layer.zip