# Copyright (c) 2025 Amazon.com
# This file is licensed under the MIT License.
# See the LICENSE file in the project root for full license information.
"""model.env is the image's baked configuration; loading it is what makes the
engine selection and the bundle's calibrated operating point reach the process.
These tests pin the loader's contract: defaults only, real environment wins."""

from __future__ import annotations

import os
from pathlib import Path

import pytest
from asr_server.model_env import load_model_env


@pytest.fixture(autouse=True)
def isolated_environ(monkeypatch: pytest.MonkeyPatch) -> None:
    """Every write load_model_env makes lands in a throwaway copy.

    A trailing ``monkeypatch.delenv`` is NOT equivalent: it records the leaked
    value at delenv time and faithfully restores the leak at teardown, which is
    exactly how ASR_ENGINE=accurate escaped into the warmup tests.
    """
    monkeypatch.setattr(os, "environ", dict(os.environ))


def _write(tmp_path: Path, body: str) -> Path:
    (tmp_path / "model.env").write_text(body, encoding="utf-8")
    return tmp_path


def test_the_baked_engine_and_operating_point_become_environment_defaults(
    tmp_path: Path,
) -> None:
    os.environ.pop("ASR_ENGINE", None)
    os.environ.pop("ASR_SPEAKER_THRESHOLD", None)
    _write(tmp_path, "ASR_ENGINE=accurate\nASR_SPEAKER_THRESHOLD=0.4\n")

    applied = load_model_env(tmp_path)

    assert applied == {"ASR_ENGINE": "accurate", "ASR_SPEAKER_THRESHOLD": "0.4"}
    assert os.environ["ASR_ENGINE"] == "accurate"
    assert os.environ["ASR_SPEAKER_THRESHOLD"] == "0.4"


def test_an_explicit_environment_variable_beats_the_baked_default(
    tmp_path: Path,
) -> None:
    os.environ["ASR_SPEAKER_THRESHOLD"] = "0.9"
    _write(tmp_path, "ASR_SPEAKER_THRESHOLD=0.4\n")

    applied = load_model_env(tmp_path)

    assert applied == {}
    assert os.environ["ASR_SPEAKER_THRESHOLD"] == "0.9"


def test_comments_blanks_and_malformed_lines_are_skipped(tmp_path: Path) -> None:
    os.environ.pop("ASR_MIN_SEGMENT_MS", None)
    _write(
        tmp_path,
        "# Generated by the LMA AsrImageSource custom resource. Do not edit.\n"
        "\n"
        "not a key value line\n"
        "ASR_MIN_SEGMENT_MS=2500\n",
    )

    applied = load_model_env(tmp_path)

    assert applied == {"ASR_MIN_SEGMENT_MS": "2500"}


def test_a_missing_file_is_not_an_error(tmp_path: Path) -> None:
    assert load_model_env(tmp_path) == {}


def test_the_model_dir_defaults_to_asr_model_dir(tmp_path: Path) -> None:
    os.environ["ASR_MODEL_DIR"] = str(tmp_path)
    os.environ.pop("ASR_ENGINE", None)
    _write(tmp_path, "ASR_ENGINE=streaming\n")

    assert load_model_env() == {"ASR_ENGINE": "streaming"}


def test_min_turn_ms_env_reaches_the_diarization_config() -> None:
    """ASR_MIN_TURN_MS used to be read by build_segmentation_config and then
    clobbered by DiarizationConfig's dataclass default at the replace() site."""
    from asr_server.diarization import build_diarization_config

    os.environ["ASR_MIN_TURN_MS"] = "1234"
    config = build_diarization_config()
    assert config.min_turn_ms == 1234
