default_agent: search_agent
agents:
  search_agent:
    name: search_agent
    entrypoint: search_agent.py
    platform: linux/amd64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::423667995321:role/AgentCorePowerUserRole
      execution_role_auto_create: true
      account: '423667995321'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
