AWSTemplateFormatVersion: "2010-09-09"

Description: Amazon Transcribe Live Meeting Assistant - LLM Prompts

Transform: AWS::Serverless-2016-10-31

Parameters:
  Domain:
    Type: String
    Default: "Default"
    AllowedValues:
      - "Default"
      - "Healthcare"
    Description: The domain of the application (optional)

  CloudWatchLogsExpirationInDays:
    Type: Number
    Default: 14
    Description: The number of days log events are kept in CloudWatch Logs.

  CustomerManagedEncryptionKeyArn:
    Type: String
    Description: ARN of the customer managed KMS key for encryption

  PermissionsBoundaryArn:
    Type: String
    Default: AWS::NoValue
    Description: >-
      (Optional) ARN of an existing IAM managed policy to use as permissions boundary for IAM roles.
      If provided, this policy will limit the maximum permissions that can be granted to IAM roles
      in this stack, providing an additional layer of security.

Resources:
  LLMPromptTemplateTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      KeySchema:
        - AttributeName: LLMPromptTemplateId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: LLMPromptTemplateId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref CustomerManagedEncryptionKeyArn
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  LLMPromptUploadRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      PermissionsBoundary: !Ref PermissionsBoundaryArn
      Policies:
        - PolicyName: allow-s3-notification-config
          PolicyDocument:
            Statement:
              Effect: Allow
              Resource:
                - !GetAtt LLMPromptTemplateTable.Arn
              Action:
                - "dynamodb:PutItem"
                - "dynamodb:UpdateItem"
        - PolicyName: SSMGetParameterPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*

  LLMPromptUploadFunction:
    Type: "AWS::Lambda::Function"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: Customer can use VPC if desired
          - id: W92
            reason: Customer can choose reserved concurrency based on their requirement.
    # checkov:skip=CKV_AWS_116: "DLQ not required for Cfn Custom Resource function"
    # checkov:skip=CKV_AWS_117: "Function does not require VPC access as it only interacts with AWS services via APIs"
    # checkov:skip=CKV_AWS_115: "Function does not require reserved concurrency as it scales based on demand"
    # checkov:skip=CKV_AWS_173: "Environment variables do not contain sensitive data - only configuration values like feature flags and non-sensitive settings"
    Properties:
      Code: ../source/lambda_functions
      Handler: llm_prompt_upload.lambda_handler
      Role: !GetAtt LLMPromptUploadRole.Arn
      Runtime: python3.12
      MemorySize: 128
      Timeout: 60
      TracingConfig:
        Mode: Active
      Environment:
        Variables:
          DOMAIN: !Ref Domain
      LoggingConfig:
        LogGroup:
          Fn::Sub: /${AWS::StackName}/lambda/LLMPromptUploadFunction
    DependsOn:
      - LLMPromptUploadFunctionLogGroup

  LLMPromptUploadFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /${AWS::StackName}/lambda/LLMPromptUploadFunction
      RetentionInDays:
        Ref: CloudWatchLogsExpirationInDays
      KmsKeyId: !Ref CustomerManagedEncryptionKeyArn

  LLMStorePromptTemplates:
    Type: "AWS::CloudFormation::CustomResource"
    Properties:
      ServiceToken: !GetAtt LLMPromptUploadFunction.Arn
      LLMPromptTemplateTableName: !Ref LLMPromptTemplateTable
      Domain: !Ref Domain
      # hash below is updated by publish.sh script- used to force tempate updates when source has changed.
      source_hash: 889bf889850f3bb3

Outputs:
  LLMPromptTemplateTableName:
    Value: !Ref LLMPromptTemplateTable
