# Copyright (c) 2025 Amazon.com
# This file is licensed under the MIT License.
"""Safe entry point for the LMA CLI.

This module deliberately avoids importing *any* third-party packages at
the module level so that the console-script wrapper generated by
setuptools/pip can always be loaded.  If a required dependency is missing
we catch the ``ImportError`` here and print a friendly message telling the
user how to install everything.
"""

from __future__ import annotations

import sys


def safe_main() -> None:
    """Wrapper around :func:`lma_cli.cli.main` with dependency checking."""
    try:
        from lma_cli.cli import main  # noqa: WPS433 (nested import is intentional)
    except ImportError as exc:
        _print_missing_dependency_error(exc)
        raise SystemExit(1) from None

    # Click's main() handles its own sys.exit
    main()


def _print_missing_dependency_error(exc: ImportError) -> None:
    """Print a user-friendly error when a dependency is missing."""
    missing = exc.name or "unknown"
    print(
        f"\n[lma-cli] Error: missing required dependency — {missing!r}\n"
        f"  {exc}\n"
        "\n"
        "It looks like the LMA CLI dependencies are not installed.\n"
        "Run the following from the LMA repo root to install everything:\n"
        "\n"
        "    make setup          # full dev environment\n"
        "    make setup-cli      # CLI packages only\n"
        "\n"
        "Or install manually with pip:\n"
        "\n"
        "    pip install -e lib/lma_sdk\n"
        "    pip install -e lib/lma_cli_pkg\n",
        file=sys.stderr,
    )
